---
#redis_host: 127.0.0.1
redis_host: "redis://redis_db"
redis_port: 6379
# Uncomment and set password if redis require it.
# redis_password: changeme

log_to_file: false

# Used to namespace the redis keys used by rails.
# see config/initializers/redis.rb
#
redis_list_namespace: "bbb_texttrack_service"
redis_jobs_list_key: "bbb_texttrack_service:caption_recordings_job"
redis_edit_jobs_list_key: "bbb_texttrack_service:caption_editing_job"

playback_list_namespace: "bbb_playback"
playback_jobs_list_key: "bbb_playback:playback_job"

default_provider: "deepspeech"

storage_dir: "/text-track-service/storage"
#storage_dir: "/D/innovation/text-track-service/captions_test"
#storage_dir: "/var/texttrackservice"
