default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5
  timeout: 100000
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  pool: 1000
  timeout: 100000

test:
  <<: *default
  database: myapp_test
  pool: 1000
  timeout: 100000

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  pool: 1000
  timeout: 100000